### ISSUE TITLE
simple way to embed task.xml into submission.xml

### ISSUE THREAD

**Issue by KBorm** [ProFormA/proformaxml#10]
There seems to be no simple way to embed the task.xml into the submission.xml without zipping or modifying the task.xml (at least remove preambel)
(=> Stud.IP with Ostfalia Praktomat)
solution: e.g. embed task.xml as base64

**Comment by schmendrik** [comment]
> There seems to be no simple way to embed the task.xml into the submission.xml

Can you elaborate on that please? 

If you are trying to use an `embedded-txt-file` element to embed a task.xml into a submission.xml, obviously you'll  need to escape markup specific entities like < and > as `&lt;` and `&gt;`. Most xml frameworks support that out of the box, depending on how you construct the xml. You can also encode the task.xml to base64 instead if you prefer that route, either way is fine.

**Comment by KBorm** [comment]
I have the following options:

1. 'external-task' does not mean embedded 
3. 'task' means that I have to remove the XML declaration from the task. I'm not sure if the namespaces are a problem, too.
2. 'included-task-file' has the following options:

2a. embedded-zip-file: zipped
2b. attached-zip-file: not embedded
2c. attached-xml-file: not embedded

embedded-txt-file is not available, isn't it?

**Comment by KBorm** [comment]
I was asked to give an example for submission.xml and task.xml. This example is now attached as zip file.
[proforma_example.zip](https://github.com/ProFormA/proformaxml/files/3392270/proforma_example.zip)

**Comment by upriss** [comment]
In our last video conference it was agreed to use this:
<xs:complexType name="included-task-file-type">
  <xs:choice> ...
    <xs:element name="embedded-xml-file" type="tns:embedded-bin-file-type"/>   ...
  </xs:choice>
