### ISSUE TITLE
student-feedback and teacher-feedback cannot be mixed

### ISSUE THREAD

**Issue by KBorm** [ProFormA/proformaxml#12]
I want to mix student-feedback and teacher-feedback for test feedback (e.g. the student should not see the stack trace for exceptions). In situations where I have more than one error (exception) for a test the xml response is invalid.

````
<subtest-response` id="junit5">
    <test-result>
        <result>
            <score>0.0</score>
        </result>
        <feedback-list>
            <student-feedback level="error">
                <title>More than one Assertion</title>
                <content format="plaintext">Test for abc123321cba expected:&lt;true&gt; but was:&lt;false&gt;</content>
            </student-feedback>
            <teacher-feedback>
                <title>Stack Trace:</title>
                <content format="plaintext">org.junit.Assert.fail(Assert.java:88) org.junit.Assert.failNotEquals(Assert.java:834) org.junit.Assert.assertEquals(Assert.java:118) de.ostfalia.zell.isPalindromTask.PalindromTest.testMultipleInput(PalindromTest.java:35) [...]</content>
            </teacher-feedback>
            <student-feedback>
                <title/>
                <content format="plaintext">Test for 121 expected:&lt;true&gt; but was:&lt;false&gt;</content>
            </student-feedback>
            <teacher-feedback>
                <title>Stack Trace:</title>
                <content format="plaintext">org.junit.Assert.fail(Assert.java:88) org.junit.Assert.failNotEquals(Assert.java:834) org.junit.Assert.assertEquals(Assert.java:118) de.ostfalia.zell.isPalindromTask.PalindromTest.testMultipleInput(PalindromTest.java:35) [...]</content>
            </teacher-feedback>
        </feedback-list>
    </test-result>
</subtest-response>

**Comment by upriss** [comment]
The change for this would be minimal. Line 1018 would need to be changed from <xs:sequence> to <xs:sequence maxOccurs="unbounded">. It would be backward compatible.

**Comment by KBorm** [comment]
Note that my issue refers to the feedback-list-type used in separate-test-feedback. But it may also affect the merged feedback.

**Comment by upriss** [comment]
An explanation in the whitepaper could be as follows:
Most likely a teacher will see all the feedback that is also provided to a student. Therefore feedback for a teacher tends to be a union of feedback for students with additional information. Instead of copying the text provided to a student into the text for the teacher, it can be beneficial to produce a continuous text for the student and add the bits for the teacher inbetween.

**Comment by upriss** [comment]
updates performed in white paper and xsd
