### ISSUE TITLE
more response-meta-data

### ISSUE THREAD

**Issue by KBorm** [ProFormA/proformaxml#13]
Some more information should be added to the response meta data: 

- timestamp 

for external submissions coming from a revision control (version control system): 

- name of version control system (e.g. git, SVN)
- version of version control system (optional)
- uri for accessing the submission (mostly same as in submission)
- revision of submission

**Comment by schmendrik** [comment]
I agree. Both the submission and response should have a date of submission/response, a (possibly optional) attribute "timestamp" in ISO 8601 UTC format. This timestamp would also serve as a revision indicator. A submission with the latest timestamp is also the latest revision of that submission.

**Comment by upriss** [comment]
In our video conference we discussed to add an optional response-datetime element in response-meta-data. The rest of this ticket relates more to issue #14
