### ISSUE TITLE
specify non-default resource limits

### ISSUE THREAD

**Issue by KBorm** [ProFormA/proformaxml#17]
Normally tests should run with limited resources for security and stability reasons. 
Some tasks might have different requirements. In order to handle those situations I would like to specify those differences.

**Comment by schmendrik** [comment]
As discussed in the video conference, resource limits can be set for each individual test in the any namespace of the [test-meta-data element](https://github.com/ProFormA/proformaxml/blob/master/Whitepaper.md#the-test-meta-data-element).
