### ISSUE TITLE
model-solutions should be optional

### ISSUE THREAD

**Issue by kkoehn** [ProFormA/proformaxml#5]
Hello,
I'm currently implementing a large portion of the `task` node in an application. 
I was wondering why an instance of `model-solution` is always required, while none of the other files (e.g. `files` or `tests`) are obligatory.
Since our application does not require `model-solutions` to be present, I always have to add a placeholder to satisfy the schema, which feels odd.

slightly offtopic: 
During testing, I tried generating a minimal `task` and this was the result. Could you please verify that it is indeed a minimal `task` and no more nodes or attributes can be removed?
```xml
<?xml version="1.0" encoding="UTF-8"?>
<task xmlns="urn:proforma:v2.0.1" uuid="">
  <title/>
  <description/>
  <proglang version=""/>
  <files>
    <file id="ms-placeholder-file" used-by-grader="false" visible="no">
      <embedded-txt-file filename=""/>
    </file>
  </files>
  <model-solutions>
    <model-solution id="ms-placeholder">
      <filerefs>
        <fileref refid="ms-placeholder-file"/>
      </filerefs>
    </model-solution>
  </model-solutions>
  <tests/>
  <meta-data/>
</task>
```

Thanks

**Comment by rghsh** [comment]
Hi kkoehn,

the decision that model-solutions are mandatory is didactically motivated. We wanted to force the task author to specify a model solution. The decision of files being optional outdates that of the mandatory model-solution.

Of course you can specify a fake model solution, but that is not in line with the format ideas.

Your minimal task seems right. I just validated it using xmllint. And yes, it seems minimal too.

**Comment by rghsh** [comment]
Perhaps we should
- either make `model-solutions` optional
- or `file` inside of `files` read as minOccurs=1

**Comment by schmendrik** [comment]
We have considered this issue internally and decided to make `model-solutions` an optional element. The reason being that we do not want to impose our didactically motivated views, as @rghsh put it, on others, especially if it makes them have to work around the issue anyway.
