### ISSUE TITLE
natural-lang is not available for binary files

### ISSUE THREAD

**Issue by KBorm** [ProFormA/proformaxml#8]
The language attribute can only be added to attached text files. So it is not possible to add binary files for different languages (e.g. pdf files) to a task.

Why is the natural-language attribute not available for all file types?

**Comment by upriss** [comment]
According to the white paper "the natural-lang attribute can be used to help the grader detect the encoding of a submitted plaintext file". This is not necessary for binary files.

**Comment by schmendrik** [comment]
@KBrom If an internationalized task needs to provide binary files such as images, PDFs etc that contain text in different languages, one can use the formats markup code to specifiy language-specific file pathes, such as `<attached-bin-file>@@@img1_filepath@@@</attached-bin-file>`, for example. Different `/<lang>/strings.txt` files would contain different file pathes (as a key-value pair) for that particular file element.
